
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles  # Map static files to Docker volume
      - media_volume:/app/media  # Map media files to Docker volume
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:17
    # environment:
    #   POSTGRES_DB: django_db
    #   POSTGRES_USER: django_user
    #   POSTGRES_PASSWORD: django_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  postgres_data:
  static_volume:
  media_volume:
