
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
#    command: >
#      bash -c "python manage.py makemigrations
#      && python manage.py migrate
#      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles  # Map static files to Docker volume
      - media_volume:/app/media  # Map media files to Docker volume
    ports:
      - "8000:8000"
#    environment:
#      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
#      - POSTGRES_DB=${POSTGRES_DB}
#      - POSTGRES_USER=${POSTGRES_USER}
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#      - POSTGRES_HOST=${POSTGRES_HOST}
#      - POSTGRES_PORT=${POSTGRES_PORT}
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:17
#    environment:
#      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
#      - POSTGRES_DB=${POSTGRES_DB}
#      - POSTGRES_USER=${POSTGRES_USER}
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#      - POSTGRES_HOST=${POSTGRES_HOST}
#      - POSTGRES_PORT=${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  postgres_data:
  static_volume:
  media_volume:
